### ISSUE TITLE
Outdated version of iron:middleware-stack

### ISSUE THREAD

**Issue by Arthelon** [ehzhang/HELPq#10]
iron:middleware-stack version listed in .meteor/versions is outdated and causes the error specified in this stackoverflow [thread](http://stackoverflow.com/questions/36031706/middleware-stack-js31-uncaught-error-handler-with-name-route-already-exists).

**Comment by josephthweatt** [comment]
I've had the same issue. The app was not allowing me to go into my profile or admin. Instead I got this message: **Oops, looks like there's no route on the client or the server for url**
Updating iron with `meteor update iron:middleware-stack` solved the problem for me. Thanks for finding that thread.

**Comment by goatandsheep** [comment]
if the bug has been updated, should we close this ticket?
