### ISSUE TITLE
Suggestion: Trim username at the login page before attempting to log in

### ISSUE THREAD

**Issue by josephthweatt** [ehzhang/HELPq#17]
Currently logging into Helpq requires you avoid spaces before and after typing in your username. So this input will not work:
username: " admin  "
password: "hunter2"

My fork has made changes so that the above input works. Of course, only the username is trimmed, not the password. If you would like to implement this change, I've included the modified code block. This change is made in client/components/login/login.js :

```function loginPassword(t){
  Meteor.loginWithPassword(
      $(t.findAll('#username')).val().trim(),
      $(t.findAll('#password')).val(),
      function(error){
        if (error){
          $(t.findAll('#password')).val("");
          t.error.set(error.reason);
        }
      }
  )
}

**Comment by ehzhang** [comment]
Sounds like a good change! Want to submit a pull request for a formal review / merge? Would be a nice addition to the contributors list!

**Comment by josephthweatt** [comment]
I could do that, but I've also made some stylistic changes to the app itself (colors, logos, etc). Will you be able to pick out the specific changes to merge? Thank you.

**Comment by ehzhang** [comment]
If you could, you can create a branch from the point of fork, and [cherry pick the commit or part of the commit](http://stackoverflow.com/questions/1526044/partly-cherry-picking-a-commit-with-git). Then you could compare that branch!

**Comment by josephthweatt** [comment]
Alright, made the request.
