### ISSUE TITLE
Problems getting Github oAuth to return to the user's page.  

### ISSUE THREAD

**Issue by josephthweatt** [ehzhang/HELPq#22]
This is my first time using Github oAuth and I'm having a bit of a problem. 

I have assigned Github OAuth's client ID and User Secret to `config.json`, and "enable" is set to true. But when I sign in with Github using the "Login With Github" button, it takes me back to the HELPq's login page instead of the homepage.

In my Oauth applications, I am setting the homepage URL to: 

http://nameofwebsite.com 

and I am setting the Authorization callback URL to:

http://nameofwebsite.com:3000    <-- the application runs on port 3000

I should also mention that when it returns to the login page, I see this in the url:
nameofwebsite.com:3000/error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application

Am I not properly assigning these URLs? Please let me know what you guys think.

**Comment by kedarv** [comment]
What was the fix?

EDIT: Found the fix! Wish there was a note about this on the README
Meteor will use `Meteor.absoluteUrl` for the redirect URL. Before running `meteor`, be sure to set your ROOT_URL environment variable like so:

`export ROOT_URL=https://helpq.hackathonurl.com`
