### ISSUE TITLE
Github OAuth Broken

### ISSUE THREAD

**Issue by drewthoennes** [ehzhang/HELPq#36]
Like #31 , the OAuth for logging in with Github doesn't seem to work and instead brings up a 404. Can I expect this to be resolved soon? I'm working on deploying HELPq for a hackathon.

**Comment by kyeb** [comment]
I actually recently deployed this for a HackMIT event and was able to get GitHub auth working (although Facebook and Google are another story). I believe I set the callback URL to the domain name the app was deployed to (https://q.hackmit.org/). 

Is your Authorization callback URL set correctly in your GitHub developer settings?

**Comment by drewthoennes** [comment]
@kyeb Thanks for the tip! I had the authorization callback set correctly, but I found a different problem with my configuration.
