### ISSUE TITLE
Save "How can we help you?" input and display while waiting 

### ISSUE THREAD

**Issue by Vervious** [ehzhang/HELPq#6]
(context: at Hack@Brown)
It would potentially be a nicer user experience for the requestee to be able to view the form submission while waiting for a mentor – just to have a reference to what he/she requested help on.

If you agree, I could implement it if you don't want to.

**Comment by Vervious** [comment]
(Also: can you enable issues in the lab6 repo?)

**Comment by ehzhang** [comment]
This would be a good feature!

**Comment by ehzhang** [comment]
Closing, added to #9
